Seagate/cortx-management-portal

- web/src/config/client_swagger.json
- web/src/config/swagger.json
Updated swagger details for users
> [CORTX] Eos 13628 updated swagger details for users

- gui/src/components/alerts/alert-details.vue
- gui/src/components/alerts/alert-history-details.vue
- gui/src/components/alerts/alert-large.vue
- gui/src/components/dashboard/dashboard.vue
- gui/src/components/health/cortx-health-menu.vue
- gui/src/components/health/cortx-health-view.vue
- gui/src/components/health/cortx-health.vue
- gui/src/components/maintenance/cortx-node-replacement.vue
- gui/src/components/maintenance/cortx-resource.vue
- gui/src/components/s3/access-key-management-iam.vue
- gui/src/components/s3/access-key-management.vue
- gui/src/components/s3/account-management.vue
- gui/src/components/s3/iam-user-management.vue
- gui/src/components/security/403.vue
- gui/src/components/security/404.vue
- gui/src/components/settings/cortx-settings.vue
- gui/src/components/settings/data-network-setting.vue
- gui/src/components/settings/dns-data-setting.vue
- gui/src/components/settings/mgmt-network-setting.vue
- gui/src/components/settings/notifications-email-setting.vue
- gui/src/components/settings/ntp-setting.vue
- gui/src/components/settings/ssl-certificate-setting.vue
- gui/src/components/udx/cortx-udx.vue
CSM UI : Fixed padding issue for all page header name
<pre>
<code>
Story Ref (if any): No 
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
- Fixed padding issue for all page header name
- Removed the height for the health table
- Updated the code
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</pre>
> [cortx1.0-dev] CSM UI:Fixed padding issue for all page header name

- gui/src/components/alerts/alert-details.vue
- gui/src/components/alerts/alert-history-details.vue
- gui/src/components/alerts/alert-large.vue
- gui/src/components/dashboard/dashboard.vue
- gui/src/components/health/cortx-health-menu.vue
- gui/src/components/health/cortx-health-view.vue
- gui/src/components/health/cortx-health.vue
- gui/src/components/maintenance/cortx-node-replacement.vue
- gui/src/components/maintenance/cortx-resource.vue
- gui/src/components/s3/access-key-management-iam.vue
- gui/src/components/s3/access-key-management.vue
- gui/src/components/s3/account-management.vue
- gui/src/components/s3/iam-user-management.vue
- gui/src/components/security/403.vue
- gui/src/components/security/404.vue
- gui/src/components/settings/cortx-settings.vue
- gui/src/components/settings/data-network-setting.vue
- gui/src/components/settings/dns-data-setting.vue
- gui/src/components/settings/mgmt-network-setting.vue
- gui/src/components/settings/notifications-email-setting.vue
- gui/src/components/settings/ntp-setting.vue
- gui/src/components/settings/ssl-certificate-setting.vue
- gui/src/components/udx/cortx-udx.vue
CSM UI : Fixed padding issue for all page header name
<pre>
<code>
Story Ref (if any): No 
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
- Fixed padding issue for all page header name
- Removed the height for the health table
- Updated the code
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</pre>
> [main] CSM UI:Fixed padding issue for all page header name

- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
CSM UI : EOS-13638
<pre>
<code>
Story Ref (if any): No 
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
- Not able to see loader, while updating user
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</pre>
> [cortx1.0-dev]EOS-13638loader icon issue

- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
CSM UI : EOS-13638
<pre>
<code>
Story Ref (if any): No 
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
- Not able to see loader, while updating user
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</pre>
> [main] EOS-13638loader icon issue

- gui/src/common/user-permissions-map.ts
- gui/src/components/navigation/nav-bar.vue
- gui/src/router.ts
<pre>
<code>
Story Ref (if any): EOS-12996 Add permission for lyve_pilot
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
lyve_pilot should be visible on permission api call response
</code>
</pre>
<pre>
<code>
Added checks for lyve_pilot from permission/api call
</code>
</pre>
<pre>
<code>
- NOT required
</code>
</pre>
> [cortx] Add permission for lyve_pilot #101

- gui/src/components/alerts/alert-comments.vue
- gui/src/components/alerts/alert-details.vue
- gui/src/components/alerts/alert-history-details.vue
- gui/src/components/alerts/alert-large.vue
- gui/src/components/dashboard/dashboard.vue
- gui/src/components/health/cortx-health-menu.vue
- gui/src/components/health/cortx-health-view.vue
- gui/src/components/health/cortx-health.vue
- gui/src/components/maintenance/cortx-node-replacement.vue
- gui/src/components/maintenance/cortx-resource.vue
- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
- gui/src/components/preboarding/license-agreement.vue
- gui/src/components/s3/access-key-management-iam.vue
- gui/src/components/s3/access-key-management.vue
- gui/src/components/s3/account-management.vue
- gui/src/components/s3/iam-user-management.vue
- gui/src/components/security/403.vue
- gui/src/components/security/404.vue
- gui/src/components/settings/cortx-settings.vue
- gui/src/components/settings/data-network-setting.vue
- gui/src/components/settings/dns-data-setting.vue
- gui/src/components/settings/mgmt-network-setting.vue
- gui/src/components/settings/notifications-email-setting.vue
- gui/src/components/settings/ntp-setting.vue
- gui/src/components/settings/ssl-certificate-setting.vue
- gui/src/components/udx/cortx-udx.vue
- gui/src/components/widgets/build-link-directive.ts
- web/src/config/client_swagger.json
- web/src/config/swagger.json
> Cortx1.0 dev

- gui/src/components/maintenance/cortx-maintenance-menu.vue
- gui/src/router.ts
- web/src/services/system/routes.ts
- web/src/services/system/system-controller.ts
<pre>
<code>
Story Ref (if any): EOS-13871
</code>
</pre>
<pre>
<code>
locally done
</code>
</pre>
<pre>
<code>
Remove Node replacement Option of GUI
</code>
</pre>
<pre>
<code>
- Commented code from UI and node API's
</code>
</pre>
<pre>
<code>
- Done locally
</code>
</pre>
> [Cortx1.0-dev] EOS-13871 changes commented for node replacement option from UI

- web/src/config/client_swagger.json
- web/src/config/swagger.json
<pre>
<code>
Story Ref (if any): Swagger ui change for access key API's
</code>
</pre>
<pre>
<code>
locally done
</code>
</pre>
<pre>
<code>
Added access key API's in Swagger
</code>
</pre>
<pre>
<code>
- Added Access key's API in following files
swagger.json and client_swagger.json
- updated user_id to user_name for DELETE API for Iam user
- Updated old_password to current_password
</code>
</pre>
<pre>
<code>
- Done locally
</code>
</pre>
> [Cortx1.0-dev]\:Swagger ui change for access key API 

- web/src/config/client_swagger.json
- web/src/config/swagger.json
Updated swagger document for alerts and health/resources
Signed-off-by: Naval Patel <naval.patel@seagate.com>
> [CORTX] Updated alerts and resource_health details

- gui/src/components/s3/bucket-creation.vue
<pre>
<code>
Story Ref (if any):Added dynamic id to bucket url td
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
-Id's to bucket url
</code>
</pre>
<pre>
<code>
- Added dynamic id to bucket url td
- increased max-width to 700 for created bucket dialog
</code>
</pre>
<pre>
<code>
- done on local
</code>
</pre>
> [Cortx1.0-dev] Added dynamic id to bucket url td

- gui/src/components/onboarding/finish.vue
- gui/src/i18n.ts
<pre>
<code>
Story Ref (if any): EOS-14255 Button title for completing Onboarding is improper
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
Button title for completing Onboarding is improper
</code>
</pre>
<pre>
<code>
Fixed camel case for ```onboarding```
</code>
</pre>
<pre>
<code>
- NOT required
</code>
</pre>
> [main] Fixes onboarding on Success msg

- web/src/config/client_swagger.json
- web/src/config/swagger.json
- web/src/middleware/api-docs.ts
<pre>
<code>
Story Ref (if any): Swagger ui change for access key API's
</code>
</pre>
<pre>
<code>
locally done
</code>
</pre>
<pre>
<code>
Added access key API's in Swagger
</code>
</pre>
<pre>
<code>
- Added Access key's API in following files
swagger.json and client_swagger.json
- updated user_id to user_name for DELETE API for Iam user
- Updated old_password to current_password
</code>
</pre>
<pre>
<code>
- Done locally
</code>
</pre>
> [main]:Swagger ui change for access key API

- gui/src/components/maintenance/cortx-maintenance-menu.vue
- gui/src/router.ts
- web/src/services/system/routes.ts
- web/src/services/system/system-controller.ts
<pre>
<code>
Story Ref (if any): EOS-13871
</code>
</pre>
<pre>
<code>
locally done
</code>
</pre>
<pre>
<code>
Remove Node replacement Option of GUI
</code>
</pre>
<pre>
<code>
- Commented code from UI and node API's
</code>
</pre>
<pre>
<code>
- Done locally
</code>
</pre>
> [main] EOS-13871 changes commented for node replacement option from UI

- gui/src/components/onboarding/system-config/data-network/data-network-ipv6.vue
- gui/src/components/onboarding/system-config/data-network/data-network.vue
- gui/src/components/onboarding/system-config/user-settings/user-setting-ldap.vue
<pre>
<code>
Story Ref (if any): EOS-14333 : Fix incorrect translations
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
Fix incorrect translations on some pages.
</code>
</pre>
<pre>
<code>
Fix miss spelled translations
</code>
</pre>
<pre>
<code>
- NOT required
</code>
</pre>
> Fix incorrect translations

- gui/src/common/regex-helpers.ts
- gui/src/components/onboarding/system-config/dns/dns-setting-config.vue
- gui/src/locales/en.json
text review changes
<pre>
<code>
Story Ref (if any):EOS-14222
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
1. Welcome!!! changed to Welcome!
2. Changed "Click on Start to proceed with on onboarding steps." to "Click Start to proceed with onboarding steps."
3. username info tooltip : one space before this sentence "The username must not be 'root' or 'Root'."
4.password info tooltip: change from "Password must contain: Minimum 8 characters, One uppercase letter, One lowercase letter, One special character, One number"
to "Password must contain: Minimum 8 characters, One uppercase letter, One lowercase letter, One special character, and One number"
5.DNS setting
there should be little bit space above "DNS server" and "search domains" inputs
</code>
</pre>
<pre>
<code>
</code> …
> [Cortx] EOS-14222UI text review changes for preboarding and onboarding page

- gui/src/components/udx/cortx-udx-registration.vue
Signed-off-by: Jayshree More <jayshree.more@seagate.com>
CSM UI :  added correct bucket name in udx dialog box
<pre>
<code>
Story Ref (if any):
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
</code>
</pre>
1)testing not done  
</code>
</pre>
> [cortx1.0-dev]added correct bucket name

- gui/src/components/udx/cortx-udx-registration.vue
CSM UI :wrong bucket name is showing on udx dialog box
<pre>
<code>
Story Ref (if any):
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
1)testing  is pending 
</code>
</pre>Signed-off-by: Jayshree More <jayshree.more@seagate.com>
> [main]added correct bucket name

- gui/src/components/dashboard/capacity-gauge.vue
<pre>
<code>
Story Ref (if any): Fixed lint error
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
fixed lint issue
</code>
</pre>
<pre>
<code>
fixed lint issue
Added type to variable
</code>
</pre>
<pre>
<code>
- NOT required
</code>
</pre>
> fixed lint issue

- gui/src/components/s3/account-management.vue
- gui/src/locales/en.json
- gui/src/models/s3.ts
CSM UI : [CSM UI] Show newly added fields after creation of s3 account
<pre>
<code>
Story Ref (if any):EOS-14748
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
1)created new s3 account
2) check in popup account id and canonical id is present or not
3) download csv file and check account and canonical id is present or not
</code>
</pre>
Signed-off-by: Jayshree More <jayshree.more@seagate.com>
> [cortx1.0-dev]:EOS-14748:: [CSM UI] Show newly added fields after creation of s3 account

- gui/src/components/maintenance/cortx-about.vue
- gui/src/locales/en.json
- gui/src/services/api-register.ts
- web/src/services/about/about-controller.ts
- web/src/services/about/routes.ts
- web/src/services/api-register.ts
CSM UI : CSM Read Unique ID from file to Display
<pre>
<code>
Story Ref (if any):EOS-14534
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
added  serial no in about section
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
1)added serial no in about section
2) added middleware 
</code>
</pre>
Signed-off-by: Jayshree More <jayshree.more@seagate.com>
> [cortx1.0-dev]EOS-14534: Added serial no in about page

- web/src/config/client_swagger.json
<pre>
<code>
Story Ref (if any): EOS-14605 Swagger UI update with error code description
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
Swagger UI update with error code description
</code>
</pre>
<pre>
<code>
-  Added description to error code
- Updated API description wherever required
- Added or removed description which are not going to applicable for any API
</code>
</pre>
<pre>
<code>
- NOT required
</code>
</pre>
> [Cortx1.0-dev] EOS-14605 Swagger UI update with error code description

- gui/src/components/maintenance/cortx-about.vue
<pre>
<code>
Story Ref (if any): EOS-15006: UI : CSM shows extra '-' before the serial number on the UI
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
UI : CSM shows extra '-' before the serial number on the UI
</code>
</pre>
<pre>
<code>
- Remove extra '-'
</code>
</pre>
<pre>
<code>
- Done with locally
</code>
</pre>
> Remove extra '-' hyphen

- gui/src/components/maintenance/cortx-about.vue
<pre>
<code>
Story Ref (if any): EOS-15006: UI : CSM shows extra '-' before the serial number on the UI
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
UI : CSM shows extra '-' before the serial number on the UI
</code>
</pre>
<pre>
<code>
- Remove extra '-'
</code>
</pre>
<pre>
<code>
- Done with locally
</code>
</pre>
> [cortx-1.0] Remove extra '-'

- gui/src/components/preboarding/license-agreement.vue
License agreement TnC text updates
> License agreement updates

- README.md
Added Codacy and APGLV3 License badges
Signed-off-by: Saumya Sunder <saumya.sunder@seagate.com>
> Added Codacy and APGLV3 License badges

- gui/src/components/udx/cortx-iam-user.vue
- gui/src/components/udx/cortx-select-create-bucket.vue
- gui/src/components/udx/cortx-udx-s3-creation.vue
- gui/src/components/udx/login-existing-s3account.vue
Signed-off-by: Shri Metta <732880@ssc-vm-1133.colo.seagate.com>
> Main build fail fixes: Fixed translation related errors.

- web/src/config/swagger.json
- web/src/services/api-register.ts
- web/src/services/ssl/routes.ts
- web/src/services/ssl/ssl-controller.ts
<pre>
<code>
Story Ref (if any): EOS-16584: Rest API to fetch SSL information
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Rest API to fetch SSL infomration
</code>
</pre>
<pre>
<code>
Exposed Rest API to fetch SSL information
API: /api/v1/tls/bundle/details
Response:
{
"cert_details": {
"subject": {
"commonName": "localhost",
"countryName": "US",
"localityName": "Denver",
"stateOrProvinceName": "Colorado",
"organizationName": "Seagate",
"organizationalUnitName": "CSM"
},
"issuer": {
"commonName": "CSM",
"countryName": "US",
"localityName": "Voronezh",
"stateOrProvinceName": "Colorado",
"organizationName": "Seagate",
"organizationalUnitName": "CSM",
"emailAddress": "csm_root_ca@mail.com"
},
"not_valid_after": "2033-10-14 16:29:14",
"not_valid_before": "2020-02-05 16:29:14", …
> EOS-16584: Rest API to fetch SSL information

- cicd/csm_web.spec
CSM UI : Update CSM RPM License Information
<pre>
<code>
Story Ref (if any):NA
</code>
</pre>
<pre>
<code>
yes
</code>
</pre>
<pre>
<code>
Incorrect License information observed for csm-web rpm
</code>
</pre>
<pre>
<code>
Updated correct License information  for csm-web 
</pre>
<pre>
<code>
[root@ssc-vm-2292 731368]# rpm  -qa --qf "%{name} : %{license}\n" | grep cortx-csm_web
cortx-csm_web : Seagate
</code>
</pre>
> Update CSM RPM License Information

- gui/package.json
- gui/src/components/preboarding/login.vue
- gui/src/components/provisioning/cortx-provisioning-menu.vue
<pre>
<code>
1. After login, user is redirected directly to s3 page.
2. Styling is broken
</code>
</pre>
<pre>
<code>
After login, the user is redirected directly to s3 page instead of dashboard. Also the styling is broken.
</code>
</pre>
<pre>
<code>
Fixed routing issue and reverted vutify version to 2.0.0
</code>
</pre>
> Fixed routing issue and reverted vutify version to 2.0.0

- web/src/services/api.ts
Add forwarding info header to CSM web requests
<pre>
<code>
Story Ref (if any):EOS-18771
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
Added client and proxy IP in headers as forwarded
</code>
</pre>
</code>
</pre>Signed-off-by:
> EOS-18771: Code changes to add x-forwarded headers while accessing csm_agent APIs

- gui/src/common/stats-utility.ts
- gui/src/components/dashboard/stats/stats-medium.vue
- gui/src/components/widgets/line-chart.vue
CSM UI : Refactor stats-utility class
<pre>
<code>
Story Ref (if any):EOS-18649
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
The current logic that handles UI unresponsive issue does not cover all cases. Need to improve the logic.
</code>
</pre>
1)remove unwanted demo data  from line chart.
2)remove switch statement from stats utility class and add short optimize logic for y2 object in line chart file 
3)optimize formatDataGenric function from stats utility class.
<pre>
<code>
</code>
</pre>
<pre>
<code>
1)added graph data 
2) open dashboard page.
3) open another tab
4) stay for 1 hrs then 2 hrs, then 3hrs . page is not unresponsive 
5) check graph with new data and old data .
</code>
</pre>Signed-off-by: Jayshree More <jayshree.more@seagate.com>
> EOS-16:849Refactor stats-utility class

- gui/src/components/widgets/line-chart.vue
- gui/src/services/api.ts
CSM UI : Login does not complete if user changes browser tab or page before its completion
<pre>
<code>
Story Ref (if any):EOS-14256
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
CSM Admin OR S3Account login does not get completed if user changes page or browser tab after clicking Submit and before completing the login. As login process is bit slow; user tend to change application OR browser tab expecting login to complete in background. To users surprise, we are showing Failed Login message.
</code>
</pre>
previously we are canceling token when tab is change because for stopping status api call. remove that logic from api.ts and added event in line-chart.vue for tab change detection 
<pre>
<code>
</code>
</pre>
<pre>
<code>
1)tested graph on dashboard
2)check if tab change …
> EOS-14256:Login does not complete if user changes browser tab or page before its completion

- web/src/services/user/routes.ts
Signed-off-by: nareshgopal <naresh.gopalakrishnan@seagate.com>
<pre>
<code>
EOS-18912: There is a bug in the PR raised for this task.
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Calls to user route is failing with 400 error.
</code>
</pre>
Before - Permissions call failed with 400
After - Permissions call succeeded
<pre>
<code>
Tested the calls to the user routes.
</code>
</pre>
> Fixed version issue in user route

- gui/src/components/preboarding/admin-user.vue
<pre>
<code>
Asterisk symbol should be present for Email Address Label while creating Admin user
</code>
</pre>
<pre>
<code>
Story Ref (if any): EOS-19429 UI: Asterisk mark for email field on preboarding screen .
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
- Asterisk symbol should be present for Email Address Label while creating Admin user
</code>
</pre>
<pre>
<code>
- Added asterisk mark for email field on preboarding screen.
</code>
</pre>
<pre>
<code>
- Go to preboarding screen.
- Verified asterisk mark for email field
</code>
</pre>
> EOS-19429 - Added required mark asterisk symbol for email field of preboarding screen

- web/src/services/s3/s3-controller.ts
> PR to fix merge issues.

- web/src/services/api-register.ts
Correct UDX SAAS URL
<pre>
<code>
EOS-20426: UDX SAAS URL is not correct
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
UDX SAAS URL is not correct
</code>
</pre>
<pre>
<code>
Corrected the UDX SAAS url from /usl/${version}/saas to /usl/${version}/udx_saas
</code>
</pre>
<pre>
<code>
Checked if the URL is accessible and working.
</code>
</pre>
Signed-off-by: Soniya Moholkar <soniya.moholkar@seagate.com>
> EOS-20426: udx saas url correction

- web/src/config/client_swagger.json
- web/src/config/swagger.json
<pre>
<code>
EOS-20570: CSM-WEB: User should able to see proper description for s3account on swagger api documents 
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Parameters of all the requests show "Could not render the component" error.
</code>
</pre>
OAS version was upgraded from 2 to 3. Syntax for the parameters and request body also differ from the previous version. It has been updated appropriately.
Before: 
Parameter component is not rendered
Request payload is not sent with the request
After:
Parameters are rendered properly
Request payload is sent along the request
<pre>
<code>
1) Verified whether the parameter component is rendered properly in each request
2) Verified whether request body is …
> EOS20570 - Issues in Swagger docs

- web/src/config/swagger.json
Add admin users to the summary
> EOS-20352: update DELETE s3accounts description

- gui/src/components/s3/account-management.vue
Signed-off-by: Mughala Azam <mughala.azam@seagate.com>
> EOS-20359 UI:Admin to delete S3 account

- .github/pull_request_template.md
- gui/src/common/health-table-headers.ts
- gui/src/common/style.css
- gui/src/components/health/cortx-health-graphical.vue
- gui/src/components/health/cortx-health-tabular.vue
- gui/src/components/health/cortx-health.vue
- gui/src/services/api-register.ts
- web/src/services/api-register.ts
- web/src/services/system/routes.ts
- web/src/services/system/system-controller.ts
> Eos 20364 health tabular view

- gui/src/common/health-table-headers.ts
- gui/src/common/style.css
- gui/src/components/health/cortx-health-tabular.vue
- gui/src/components/health/cortx-health.vue
- gui/src/services/api-register.ts
- web/src/services/api-register.ts
- web/src/services/system/routes.ts
- web/src/services/system/system-controller.ts
> EOS-20364: Health tabular view on UI

- gui/src/components/maintenance/cortx-auditlog.vue
- web/src/services/audit/routes.ts
- web/src/services/audit/s3-audit-log-headers.json
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ Y EOS-21195
- _Describe the problem this patch intends to solve._ This would solve the display issue in S3 audit logs GUI.
- _For Bug describe the fix here._ Adding a schema for S3 audit log headers would solve this issue.
- …
> Fixed display issue in S3 audit logs

- gui/src/services/api-register.ts
- _Describe the problem this patch intends to solve. Update url to get cluster health. …
> EOS-21360: Update url to get cluster health.

- gui/src/components/settings/settings.json
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ Y EOS-21141
- _Describe the problem this patch intends to solve._ This patch fixes the wrong UI text displayed for mandatory field
- _For Bug describe the fix here._ Removing the unwanted portions in text for mandatory field
- …
> EOS-21141: Fixed error in UI text for mandatory field

- gui/src/common/health-table-headers.ts
- gui/src/common/style.css
- gui/src/components/health/cortx-health-tabular.vue
- gui/src/components/health/cortx-health.vue
- gui/src/services/api-register.ts
- web/src/services/api-register.ts
- web/src/services/system/routes.ts
- web/src/services/system/system-controller.ts
- Merge f10b to main
- _PR is self-reviewed? Yes/No? Yes
-  _Check if the description is …
> EOS-16772: Merge f10b to main

- gui/src/common/consts.ts
- gui/src/common/style.css
- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
- gui/src/models/download.ts
- gui/src/models/user-Details.ts
> eos-20367-sorting-filtering-user-table-1

- gui/src/components/s3/account-management.vue
- gui/src/components/udx/cortx-udx-s3-creation.vue
> EOS-21154: Adding account and canonical ID to download csv file

- gui/src/components/health/cortx-health-graphical.vue
> EOS-22060: ID text breaking

- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_EOS-22097
- _Describe the problem this patch intends to solve._Create CSM User view loader and default selection issue
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]:_N
- _Coding conventions are followed and code is consistent. Yes/No?_Yes
- _Confirm All CODACY errors are resolved. Yes/No?_Yes
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_No
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No?_No
- _Confirm Testing was performed with installed RPM. Yes/No?_No
- _Confirm all the ut/regression/smoke test has been performed [Y/N]_N
- _PR is …
> EOS-22097 Create CSM User view loader and default selection issue

- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS 22100
- _Describe the problem this patch intends to solve._ CSM User update role issue
- _GitHub Issue is …
> EOS 22100 CSM User update role issue

- gui/src/components/s3/access-key-management.vue
> EOS-20618: Updated table header for access key details table

- gui/src/components/header/cortx-header-dropdown.vue
- gui/src/components/s3/account-management.vue
- gui/src/locales/en.json
- gui/src/mixins/logout.ts
- gui/src/store/modules/user-login.ts
- Multiple unsupported feature calls are being made. Also every time user navigates to another page, unsupported feature call is made.
- Multiple unsupported feature calls are being made. Also every time user navigates to another page, unsupported feature call is made.
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]: N
- …
> EOS-21172: Fixed multiple unsupported feature calls.

- gui/src/common/unsupported-feature.ts
- gui/src/components/maintenance/cortx-maintenance-menu.vue
- gui/src/components/maintenance/cortx-software.vue
- gui/src/components/navigation/nav-bar.vue
- gui/src/components/onboarding/system-config/firmware/firmware.vue
- gui/src/components/settings/cortx-settings-menu.vue
> EOS-21972: Updated feature IDs

- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
- gui/src/components/s3/account-management.vue
> EOS-20621: Fixed double clicked issue for reset/update password pop ups

- gui/src/common/unsupported-feature.ts
- gui/src/components/header/cortx-header-dropdown.vue
- gui/src/components/maintenance/cortx-maintenance-menu.vue
- gui/src/components/maintenance/cortx-software.vue
- gui/src/components/navigation/nav-bar.vue
- gui/src/components/onboarding/system-config/firmware/firmware.vue
- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
- gui/src/components/s3/access-key-management.vue
- gui/src/components/s3/account-management.vue
- gui/src/components/settings/cortx-settings-menu.vue
- gui/src/locales/en.json
- gui/src/mixins/logout.ts
- gui/src/store/modules/user-login.ts
> Merge Main to Stable 07-07-2021

- gui/src/components/health/cortx-health-graphical.vue
> EOS-22111: Consistency on collapse and expand icons for health graph

- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-22065
- _Describe the problem this patch intends to solve. Search and filter for csm users not working as expected
- _For Bug describe the fix here._ 
- _Coding conventions are followed and code is consistent. Yes/No?_ YES
- _Confirm All CODACY errors are resolved. Yes/No?_ YES
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No?_ NO
- _Confirm all the ut/regression/smoke test has been performed [Y/N]_ NO
- _PR is …
> EOS-22065 R2:Build#Main1454: Search and filter for csm users not working as expected

- web/src/config/swagger.json
- [EOS-22204](https://jts.seagate.com/browse/EOS-22204): Stable 251: R1: Incorrect CSM request body for POST /csm/users on Swagger
- Incorrect CSM request body for POST /csm/users on Swagger
- Change the 'roles' field for User requests to 'role'.
-  _Check if the description is clear and explained._ …
> EOS-22204: update 'roles' to 'role' for user requests in BE swagger

- gui/src/components/header/header-bar.vue
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-22221
- _Describe the problem this patch intends to solve._ Dropdown menu is over the cortx-header. 
- _For Bug describe the fix here._ z-index of cortx-header is increased
- _Confirm Testing was performed with installed RPM. …
> EOS:22221 - Increased the z-index of cortx-header

- gui/src/common/error-handler.ts
- gui/src/components/maintenance/cortx-auditlog.vue
- gui/src/components/widgets/cortx-data-table.vue
Reverts Seagate/cortx-management-portal#439
> Revert "Audit logs bug fix - Sorting and filtering"

- gui/src/common/error-handler.ts
- gui/src/components/maintenance/cortx-auditlog.vue
- gui/src/components/widgets/cortx-data-table.vue
- Raising PR on behalf of @NareshGopal 
- Following issues are fixed:
- If there is an error after API call, the loader does not go off and error message is not shown.
- Issue with sorting
- Issue with filtering 
- Fixed issue in sort and no call is made if none of the columns are filterable.
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]: NA
- _Coding conventions are followed and code is consistent. Yes/No? Y
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No? Yes
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No? Yes
- …
> EOS-21280: Audit logs bug fix - Sorting and filtering.

- gui/src/components/preboarding/login.vue
- gui/src/locales/en.json
- gui/src/store/modules/user-login.ts
> Reset password after first time login

- gui/src/components/preboarding/login.vue
- gui/src/locales/en.json
- web/src/services/login/routes.ts
> test-pr- For testing purpose only

- gui/src/components/onboarding/onboarding.json
- gui/src/components/onboarding/system-config/ssl-certificate/upload-ssl-config.vue
- The onboarding process gets stuck at step 2 as SSL certificate upload feature is unsupported and the status api fails.
- As the SSL certificate upload feature is unsupported, it was needed to specifically handle this by checking if the feature is supported and then making the API call.
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]: NA
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No? Yes
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No? Yes
- _Confirm …
> EOS-23147: Onboarding process getting stuck at SSL certificate upload step.

- web/src/services/api.ts
Signed-off-by: Soniya Moholkar <soniya.moholkar@seagate.com>
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-22619
- Payload should be inserted in CSM audit logs
1. If the request body is not present, set the content length to 0.
2. If query params are not present, the content length will be checked to check if the request body is present. If request body is present, it will be gotten from the request.
3. This payload will be inserted in audit logs.
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_ Yes
- _Confirm Test Cases cover Happy Path, Non-Happy Path and …
> EOS-22619: Content length set only if request body is not empty

- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
- gui/src/models/download.ts
… search box
- _Describe the problem this patch intends to solve._ Filters are not cleared when the search box above the table is cleared.
- _For Bug describe the fix here._ 
- Search on type functionality was implemented in cortx-data-table component in PR #446 
- Few changes have been made on the filter call back function in user-setting-local file to clear the filters when the search box is cleared
- _Confirm All CODACY errors are resolved. …
> EOS-22207: Modified filter callback in user setting to clear filters on clearing search box

- gui/src/assets/action-icon.svg
- gui/src/components/health/cortx-health-graphical.vue
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-22644
- _Describe the problem this patch intends to solve._  Show action start stop on graph nodes.
- _For Bug describe the fix here._ Added Cluster start stop icons to the graph node.
- _For feature, post the link to the solution page._ NA
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No?_ Yes
- _Confirm Testing was performed with …
> EOS-22644: Added actions for start and stop cluster

- gui/src/components/preboarding/login.vue
- gui/src/locales/en.json
- gui/src/store/modules/user-login.ts
- web/src/services/login/routes.ts
- _Describe the problem this patch intends to solve._  The user who logs in to the CSM for the first time and with the login API response as  {"reset_password": false } will be eligible to reset password.
- _For Bug describe the fix here._ - Show reset password pop up with 'New Password', 'Confirm Password' fields with Reset button.
- _Confirm that Test Cases are added (for both the cases, fix and …
> EOS-23102: Reset password after first time login

- gui/package-lock.json
- gui/package.json
- gui/src/common/error-handler.ts
- gui/src/components/maintenance/cortx-auditlog.vue
- gui/src/components/onboarding/onboarding.json
- gui/src/components/onboarding/system-config/ssl-certificate/upload-ssl-config.vue
- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
- gui/src/components/widgets/cortx-data-table.css
- gui/src/components/widgets/cortx-data-table.vue
- gui/src/models/download.ts
- gui/src/store/modules/download.ts
- web/src/services/api.ts
- web/src/services/audit/audit-controller.ts
- web/src/services/audit/routes.ts
> Merge Main to Stable 30-07-2021

- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
- _Describe the problem this patch intends to solve._  Admin was able to change self role, which is expected to be disabled.
- _For Bug describe the fix here._ 
- have disabled the role change for admin for self, so if the admin logs in he can change role of other admins, mangers, monitor but not his own.
- _Confirm Test …
> EOS-23051: Role change for self disabled for admin.

- web/src/config/client_swagger.json
- web/src/config/swagger.json
- _Describe the problem this patch intends to solve._ 
- Unable to execute any command with authorization from Swagger document. 
- Fixed the issue by updating the documentation as mentioned in OAS3 for authorization.
- _Confirm Testing was performed with …
> EOS-23046: Fixed issue in authorization in Swagger documentation

- web/src/config/client_swagger.json
- web/src/config/swagger.json
…s3_account_id}
-  
- Request description for the S3 accounts request need to be updated correctly as per the restrictions.
- Request description has been updated properly as mentioned in the bug description.
- _Confirm Test …
> EOS-22558: Changed the description for PATCH and DELETE calls for /s3_accounts/{s3_account_id}

- gui/src/common/regex-helpers.ts
- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
- web/src/config/client_swagger.json
- web/src/config/swagger.json
- web/src/services/s3/routes.ts
> Merge Main to Stable: 09-08-2021

- cicd/build.sh
- cicd/csm_web.spec
- web/conf/csm_web.py
- web/conf/csm_web_setup.py
- web/conf/setup.yaml
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-22900
- _Describe the problem this patch intends to solve._ 
- CSM Web setup interfaces should be exposed for following mini-provisioning steps
- post_install
- prepare
- config
- init
- test
- reset
- cleanup (pre-factory)
- pre_upgrade
- post_upgrade
CSM web setup interfaces are exposed as defined in https://seagate-systems.atlassian.net/wiki/spaces/PRIVATECOR/pages/85000402/Mini-Provisioner+ConfStore+Keys
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_ 
- _Confirm Testing was …
> EOS-22900: CSM Web setup mini-provisioning interfaces

- gui/src/components/alerts/alert-details.vue
- gui/src/components/alerts/alert-history-details.vue
- gui/src/components/alerts/alert-large.vue
- Alerts with 'fru' module_name should be replaced with 'hw' in alerts components in GUI. 
- _Confirm Testing was performed with installed RPM. Yes/No?_ No
- _Confirm all the ut/regression/smoke test has been …
> EOS-23292: Adopt resource-type change from fru to hw, where ever applicable in UI side

- gui/src/locales/en.json
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-23380
- _Describe the problem this patch intends to solve._ Need to change the reset button to update on change password pop-up
- On the change password pop-up, change the reset button to "update." So in the file en.json, I simply modify "reset" to "Update."
- …
> EOS-23380 R2:#Custom Build 2223:Need to change the reset button to update on change password pop-up

- web/src/services/api.ts
…rties in it.
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-23272
- _Describe the problem this patch intends to solve._ 
- Delete requests from GUI are failing 
- There was a bug in setting up the content length of empty request body. It has been addressed. 
- _Confirm Test Cases cover Happy Path, Non-Happy Path and …
> EOS-23272: Request body for delete request will be assigned only if it has properties in it.

- gui/src/mixins/cluster-management.ts
- Implemented node start operation and fixed one bug in node stop operation.
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]: N
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No? Yes
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No? Yes
- _Confirm Testing was performed with installed RPM. Yes/No? Yes
- _Confirm all the ut/regression/smoke test has been performed [Y/N] Yes
- _PR is self-reviewed? Yes/No? Yes
- _GitHub Issue …
> EOS-22646: Implemented node start.

- web/conf/csm_web.py
Signed-off-by: Soniya Moholkar <soniya.moholkar@seagate.com>
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-22905
- It will expose test interface for csm_web which will run specified test plan
Test interface will accept the test plan and execute it.
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_ Yes
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No?_ Yes
- _Confirm Testing was performed with installed RPM. Yes/No?_ Yes
- http://eos-jenkins.colo.seagate.com/job/Cortx-PR-Build/job/cortx-management-portal/128/console
- 
- _Confirm …
> EOS-22905: Implemented test interface

- gui/src/components/widgets/cortx-message-dialog.vue
- _Describe the problem this patch intends to solve._ When user fills some wrong details while editing details and try to submit the form the error coming from the server is hidden behind the form modal.
- _For Bug describe the fix here._ Visibility for error modal is given top priority.
- _Confirm …
> Eos-23521 : Error modal on top of form modals.

- gui/src/components/widgets/cortx-data-table.vue
- _Describe the problem this patch intends to solve._ Table in manage user screen is not getting rendered properly.
- _For Bug describe the fix here._ 'actionGroup' getter had issue in undefined check. It has been fixed.
- …
> EOS-25086: Fixed the table rendering issue in manage user screen

- gui/src/components/widgets/cortx-data-table.vue
> Fixed undefined check issue in actionGroup getter. (#506)

- gui/src/components/cortx-default.vue
- gui/src/components/dashboard/cortx-dashboard-alert-card.vue
- gui/src/components/dashboard/cortx-dashboard-capacity-gauge.vue
- gui/src/components/dashboard/cortx-dashboard-cluster-health-card.vue
- gui/src/components/dashboard/cortx-dashboard.vue
- gui/src/models/performance-stats.ts
- gui/src/router.ts
- gui/src/shims-vue.d.ts
- gui/src/store/modules/performance-stats.ts
- Modify the capacity widget as mentioned in the design https://www.figma.com/file/ptVXVm0FpIIle1hZKeZqgq/LR-Theme-Redesign-Options?node-id=0%3A1
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design
> EOS-26764: Modified the capacity widget and dashboard widget placements

- gui/src/components/widgets/line-chart.vue
- Value selected for performance chart was mislabeled in thumbnails.
-  Fixing the label mismatch.
> EOS-13991: label fix for performance chart

- whitesource.config
Signed-off-by: Swanand S Gadre <swanand.s.gadre@seagate.com>
- Problem statement
"experiment" folder is excluded from folder scan, however whitesource scan is still reporting vulnerabilities under
cortx-management-portal/experiments/stats-gui-c3-poc/node_modules/color-string/package.json
Based on feedback from whitesource ticket following settings needs to be added to whitesource.config
npm.ignoreDirectoryPatterns=*/cortx-management-portal/experiments//.json
npm.resolveDependencies=true
So using this defect, updating the setting.
-  For Bug, Describe the fix here.
-  For Feature, Post the link for design
https://jts.seagate.com/browse/EOS-26833
-  [X] Coding conventions are followed and code is consistent
basic whitesource.config changes are …
> Update whitesource configuration

- src/assets/DummyData.json
- src/components/alerts/LrAlert.vue
- src/components/alerts/LrAlertComment.model.ts
- src/components/alerts/LrAlertComments.vue
- src/components/alerts/LrAlertDetails.vue
- src/components/alerts/LrAlertDialog.vue
- src/components/alerts/LrAlertInformation.vue
- src/components/shared/LrSvgIcon/LrSvgIcon.vue
- Addition of comment modal and data modal for alert page.
- Created the structure and component which can be reused as required for alert component
> Eos 28612 : comment and data modal for alert page.

- src/App.constant.ts
- src/App.vue
- src/components/shared/SgtNavigationDrawer/SgtNavigationDrawer.vue
- src/components/shared/SgtNavigationDrawer/SgtNavigationDrawerItem.model.ts
- Current implementation of side nav was specific to LR. It required to be more generic.
-  For Feature, Post the link for design
> EOS-29218: navigation drawer made generic

- src/components/alerts/LrAlert.constant.ts
- src/components/alerts/LrAlert.vue
- src/components/shared/LrDataTable/LrDataTable.constant.ts
- src/components/shared/LrDataTable/LrDataTable.vue
- src/components/shared/LrDataTable/LrDataTableFilterSortPag.model.ts
- Pagination sorting and design fixes for data table
> EOS-28903 : data table design and feature fixes

- src/assets/DummyData.json
- src/assets/icons/delete-green.svg
- src/assets/icons/green-tick.svg
- src/components/alerts/LrAlert.constant.ts
- src/components/alerts/LrAlert.vue
- src/components/manage/s3/LrS3.constant.ts
- src/components/manage/s3/LrS3Account.vue
- src/components/shared/LrDataTable/LrDataTable.constant.ts
- src/components/shared/LrDataTable/LrDataTable.vue
- src/components/shared/LrSvgIcon/LrSvgIcon.vue
- src/router/index.ts
- src/utils/CommonUtilFunctions.ts
- Migration of S3 account page to new design and functionality.
-  [Figma design](https://www.figma.com/file/PX70qpneKe6HuVezq4hB2a/S3-Account-Screens-Tab-with-S3-Login?node-id=0%3A179)
> Eos-29361: s3 account page design upgrade

- src/lib/components/SgtBreadCrumb/SgtBreadCrumb.vue
- src/scss/style.scss
- There is an empty scroll bar on the extreme right in the application which has to be removed.
- The auto-scroll feature was enabled on the HTML element to fix the issue.
> CORTX-29618: Fixed empty scroll bar issue

- package-lock.json
- src/assets/DummyData.json
- src/components/health/LrHealthTabular.vue
- src/components/manage/LrManageUser.vue
- src/components/manage/s3/LrBuckets.vue
- src/components/manage/s3/LrIAMUser.vue
- src/components/manage/s3/LrS3.constant.ts
- src/components/manage/s3/LrS3Access.vue
- src/components/manage/s3/LrS3Account.vue
- src/components/manage/s3/LrS3User.model.ts
- src/components/manage/s3/LrS3UserForm.vue
- src/lib/components/SgtDataTable/SgtDataTable.vue
- src/lib/components/SgtDialog/SgtDialog.constant.ts
- src/lib/components/SgtSvgIcon/SgtSvgIcon.vue
- src/lib/services/CommonUtilFunctions.ts
- src/scss/style.scss
- Lr buckets page is redesigned and updated.
[S3-screens](https://seagate-systems.atlassian.net/wiki/spaces/LR/pages/938935017/S3+Account+User+Manage+Screens)
> EOS-29363: Lr bucket page completed

- src/components/manage/s3/LrS3.constant.ts
- src/components/manage/s3/LrS3Access.vue
- src/lib/components/SgtToggle/SgtToggle.vue
- toggle component created to match the UX design
> Sgt toggle component added
