- web/src/config/client_swagger.json
- web/src/config/swagger.json
<pre>
<code>
Story Ref (if any): EOS-13692: Swagger- Show audit logs for csm GET query not getting executed even after providing the required fields
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Audit logs not working in swagger
</code>
</pre>
<pre>
<code>
Removed duplicate parameter
</code>
</pre>
<pre>
<code>
- done on local
</code>
</pre>
> [Cortx1.0-dev]EOS-13692: Swagger- Show audit logs for csm GET query not getting executed even after providing the required fields

- web/src/config/client_swagger.json
- web/src/config/swagger.json
<pre>
<code>
Story Ref (if any): EOS-13692: Swagger- Show audit logs for csm GET query not getting executed even after providing the required fields
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Audit logs not working in swagger
</code>
</pre>
<pre>
<code>
Removed duplicate parameter
</code>
</pre>
<pre>
<code>
- done on local
</code>
</pre>
> [main]EOS-13692: Swagger- Show audit logs for csm GET query not getting executed even after providing the required fields

- gui/src/components/preboarding/license-agreement.vue
- gui/src/components/widgets/build-link-directive.ts
<pre>
<code>
Story Ref (if any): EOS-13492 : Create framework for configuring License text based on deployment type and should be configurable
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
Need a generic template for license text.
</code>
</pre>
<pre>
<code>
Added a generic template for license text.
{
heading: "",
sub_heading: "",
sections: [
{
paragraph_text: {
title: "",
text: ""
}
},
{
bulleted_text: {
title: "",
texts: [
{
title: "",
texts: ["", ""]
}
]
}
}
]
}
</code>
</pre>
<pre>
<code>
- NOT required
</code>
</pre>
Signed-off-by: Shri Bhargav Metta <shri.metta@seagate.com>
> [cortx1.0-dev] EOS-13492: Adding generic template to show license.

- gui/src/components/preboarding/license-agreement.vue
- gui/src/components/widgets/build-link-directive.ts
<pre>
<code>
Story Ref (if any): EOS-13492 : Create framework for configuring License text based on deployment type and should be configurable
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
Need a generic template for license text.
</code>
</pre>
<pre>
<code>
Added a generic template for license text.
{
heading: "",
sub_heading: "",
sections: [
{
paragraph_text: {
title: "",
text: ""
}
},
{
bulleted_text: {
title: "",
texts: [
{
title: "",
texts: ["", ""]
}
]
}
}
]
}
</code>
</pre>
<pre>
<code>
- NOT required
</code>
</pre>
Signed-off-by: Shri Bhargav Metta <shri.metta@seagate.com>
> [main] EOS-13492: Adding generic template to show license.

- web/src/config/client_swagger.json
- web/src/config/swagger.json
<pre>
<code>
Story Ref (if any): EOS-11603: CSM: Edit comment using patch for Alert command is not working
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Edit comment using patch for Alert command is not working
</code>
</pre>
<pre>
<code>
Removed comments from request body of old API /alerts/{alert_id}
</code>
</pre>
<pre>
<code>
- done on local
</code>
</pre>
> [Cortx1.0-dev] EOS-11603: CSM: Edit comment using patch for Alert command is not working

- gui/src/components/maintenance/cortx-resource.vue
Signed-off-by: Jayshree More <jayshree.more@seagate.com>
CSM UI : Node names Under drop-downs on System maintenance page should display hostname /FQDN instead of srvnode1/2
<pre>
<code>
Story Ref (if any):EOS-13768
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
1)tested  with back-end data
</code>
</pre>
> [cortx]:Node names Under drop-downs on System maintenance page should display hostname /FQDN instead of srvnode1/2

- gui/src/components/maintenance/auditlog.vue
CSM UI : Auditlog page does not show any loader on screen and View button is enabled
<pre>
<code>
Story Ref (if any):EOS-14047
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Auditlog page does not show any loader on screen and View button is enabled
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
1)tested  audit log page loader shown or not  
</code>
</pre>
> Cortx 14047:Auditlog page does not show any loader on screen and View button is enabled

- gui/src/components/maintenance/cortx-about.vue
<pre>
<code>
Story Ref (if any): EOS-14046 About page goes blank for sometime while fetching data
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
About us page should not be blank ever, even if it is fetching data.
</code>
</pre>
<pre>
<code>
Set data with versionDetails instead of just variable and set values empty strings.
</code>
</pre>
<pre>
<code>
- NOT required
</code>
</pre>
> [cortx-1.0] Resolve empty about page

- gui/src/components/alerts/alert-details.vue
- gui/src/components/alerts/alert-history-details.vue
<pre>
<code>
Story Ref (if any): EOS-14190
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
Alert details showing blank on CSM GUI for raid integrity alert.
</code>
</pre>
<pre>
<code>
Removed temporary logic to replace single quote with double quote.
</code>
</pre>
<pre>
<code>
- NOT required
</code>
</pre>
Signed-off-by: Shri Bhargav Metta <shri.metta@seagate.com>
> [cortx1.0-dev] EOS-14190: Alert details showing blank on CSM GUI

- gui/src/components/maintenance/cortx-about.vue
<pre>
<code>
Story Ref (if any): EOS-14046 About page goes blank for sometime while fetching data
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
About us page should not be blank ever, even if it is fetching data.
</code>
</pre>
<pre>
<code>
Set data with versionDetails instead of just variable and set values empty strings.
</code>
</pre>
<pre>
<code>
- NOT required
</code>
</pre>
> [main] Resolve empty about page

- gui/src/components/maintenance/auditlog.vue
CSM UI : Auditlog page does not show any loader on screen and View button is enabled
<pre>
<code>
Story Ref (if any):EOS-14047
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Auditlog page does not show any loader on screen and View button is enabled
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
1)tested  audit log pages   
</code>
</pre>Signed-off-by: Jayshree More <jayshree.more@seagate.com>
> [Main]EOS-14047-Auditlog page does not show any loader on screen and View button is enabled

- gui/src/store/modules/system-configuration.ts
<pre>
<code>
Story Ref (if any): 
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
Send Test Mail Functionality Showing wrong error message even though the functionality is working
</code>
</pre>
<pre>
<code>
Increased the timeout of send test mail api to 2 minutes.
</code>
</pre>
<pre>
<code>
- NOT required
</code>
</pre>
Signed-off-by: Shri Bhargav Metta <shri.metta@seagate.com>
> [main] EOS-14144: Send test mail wrong error message issue fix.

- gui/src/components/dashboard/capacity-gauge.vue
Capacity chart legend color issue
<pre>
<code>
Story Ref (if any):EOS-14574
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
CSM GUI: Color of capacity tile and used capacity on the dashboard is mismatch when used capacity is at 50 % </code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
tested on locally
</code>
> [CORTX] EOS-14574 changes for capacity chart legend color issue

- gui/src/components/header/header-bar.vue
<pre>
<code>
Story Ref (if any): EOS-15330 (CSM: In CSM GUI, for s3 login, username does not appear clearly, its seen half)
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
Login name is not seen properly in header bar
</code>
</pre>
<pre>
<code>
</code>
</pre>
<pre>
<code>
- NOT required
</code>
</pre>
> [main] EOS-15330-fixed header login name issue

- gui/src/components/udx/cortx-udx-details.vue
- gui/src/components/udx/cortx-udx-registration.vue
- gui/src/components/udx/cortx-udx.vue
- gui/src/locales/en.json
<pre>
<code>
Story Ref (if any): EOS-15339: CSM: GUI needs to have Lyve Pilot instead of UDX in LyvePilot tab. Bucket name should not have ldp at the beginning
</code>
</pre>
<pre>
<code>
NOT Required
</code>
</pre>
<pre>
<code>
Need to remove all terms and text related to UDX and add expansion panel on sumary page
</code>
</pre>
<pre>
<code>
Replace UDX with LDP and add expansion to summary page
</code>
</pre>
<pre>
<code>
- NOT required
</code>
</pre>
> Replace UDX with LDP and add expansion to summary page

- web/src/services/websocket/socket-service.ts
<pre>
<code>User not able to login after the system is under continuous small/moderate load
from third party application from last 9-10 days.
</code>
</pre>
<pre>
<code>
- The issue is due to file descriptors. Process has opened too many files (file descriptors) and cannot open new ones. The open file limit for a current user is 1024.
- This is due to dangling websocket connections between csm_web and csm_agent that do not get closed
</code>
</pre>
<pre>
<code>
- The solution is to explicitly close the connections when the client (gui) socket connection is closed. 
</code>
</pre>
<pre>
<code>
- Tested by reloading the ui page and checking if the existing socket connection between web and agent gets closed and new connection is created. 
</code>
</pre>
<pre>
<code>
No
</code>
</pre> …
> [cortx-1.0]EOS-17346: Unable to login to CSM GUI with existing credentials.

- web/src/services/websocket/socket-service.ts
<pre>
<code>User not able to login after the system is under continuous small/moderate load
from third party application from last 9-10 days.
</code>
</pre>
<pre>
<code>
- The issue is due to file descriptors. Process has opened too many files (file descriptors) and cannot open new ones. The open file limit for a current user is 1024.
- This is due to dangling websocket connections between csm_web and csm_agent that do not get closed
</code>
</pre>
<pre>
<code>
- The solution is to explicitly close the connections when the client (gui) socket connection is closed. 
</code>
</pre>
<pre>
<code>
- Tested by reloading the ui page and checking if the existing socket connection between web and agent gets closed and new connection is created. 
</code>
</pre>
<pre>
<code>
No
</code>
</pre> …
> [main]EOS-17346: Unable to login to CSM GUI with existing credentials.

- gui/src/components/s3/account-management.vue
- gui/src/components/s3/iam-user-management.vue
- gui/src/components/s3/s3.json
S3 and CSM UI : Remove CSM users get call from s3 and correction of success message for reset password
<pre>
<code>
Story Ref (if any): EOS-18713 UI: Reset password success message correction and removing get csm users call from S3
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
- Account name in success message as 'undefined' for reset password functionality.
- Extra get call for CSM users on s3 accounts tab for S3 login
</code>
</pre>
<pre>
<code>
- Reset password success message showing name of account for which password is reset.
- Removed CSM users get call from s3 accounts. 
</code>
</pre>
I am user reset password:
S3 account reset password:
<pre>
<code>
- Reset password success message showing account name
- Get call for CSM users is removed
</code>
</pre>
Signed-off-by: …
> EOS 18713 Reset password success message correction and removing get csm users call from S3

- gui/src/components/header/header-bar.vue
S3 UI : Remove Alert API get call from s3 which was unwanted.
<pre>
<code>
Story Ref (if any): EOS-19052 UI: Alerts Api getting called when logged -in with S3 account user which is not required.
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
- Alerts API getting called when logged-in with S3 account user which is returning 403 error and not required as s3 account user does not have access to alerts.
- R2:Error on S3 account user Login with Some API failure .
</code>
</pre>
<pre>
<code>
- Removed Alert API get call from S3 and hence error on login also removed.
- User should get logged in with no any errors.
</code>
</pre>
<pre>
<code>
- Logged in to the S3 account and verified that no alerts API is getting called.
- User is now able to login with no any errors.
</code>
</pre> …
> Alert API is removed from S3 account login

- gui/src/services/api-register.ts
- gui/src/services/api.ts
<pre>
<code>
EOS-19167: GUI REST API Movement to V2 REST API version
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
CSM-Agent and CSM-Web now supports v2 version of API. CSM-GUI needs to be updated to make calls to v2.
</code>
</pre>
<pre>
<code>
1) After making the change, checked whether the calls in GUI are made to /api/v2 path.
</code>
</pre>
> EOS-19167 GUI update to make calls to v2 version of API

- gui/src/components/s3/bucket-creation.vue
CSM UI :Delete Bucket Policy button remains in disabled state after adding bucket policy to the bucket and only getting enable after page refresh
<pre>
<code>
Story Ref (if any):EOS-19101
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Delete Bucket Policy button remains in disabled state after adding bucket policy to the bucket and only getting enable after page refresh
</code>
</pre>
previous screen when bucket policy update :
latest screen if bucket policy update:
if policy not set previously delete button will disable 
<pre>
<code>
</code>
</pre>
<pre>
<code>
1)created new bucket
2) added bucket policy
3) update bucket policy and close the popup
4)gain click on edit icon and open bucket policy  popup
5) check delete button is enable or not
</code>
</pre>Signed-off-by: …
> EOS-19101:Delete Bucket Policy button remains in disabled state after adding bucket policy to the bucket and only getting enable after page refresh

- web/src/config/client_swagger.json
- web/src/config/swagger.json
- web/src/middleware/api-docs.ts
<pre>
<code>
EOS-18971: CSM-Web: Update Swagger documentation to support v2 version
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
A small issue occurred while updating the Swagger document. The label for dropdown should be 'Base Path' instead of 'Servers'. Also, '/api/v2' should be the default path.
</code>
</pre>
Before making the change
After making the change
<pre>
<code>
1) Checked whether the dropdown label is displayed as 'Base Path'
2) Checked whether '/api/v2' is the default path.
</code>
</pre>
> Included options parameter in swaggerUi.setup

- gui/src/components/navigation/nav-bar.vue
- gui/src/router.ts
<pre>
<code>
On Click on Manage menu IAM users and Buckets tab are getting vanished for S3 account users
</code>
</pre>
<pre>
<code>
Story Ref (if any): EOS-19095 UI: On click of manage, 'manage/s3' should be shown for s3 accounts  and 'manage/' for CSM users.
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
- On Click on Manage menu IAM users and Buckets tab are getting vanished for S3 account users
</code>
</pre>
<pre>
<code>
- Corrected routing path for manage navigation menu:
- For CSM users: '/manage'
- For S3 users: '/manage/s3'
</code>
</pre>
<pre>
<code>
- Login to S3 accounts UI
- Click on manage link
- Verified router path '/manage/s3' and Bucket and I AM User tabs are not vanishing
</code>
</pre>
> EOS-19095 - Manage path is updated based on CSM and S3 account login

- gui/src/components/maintenance/cortx-software.vue
<pre>
<code>
"unknown_desc" is always shown against last update description when we upload or perform software update
</code>
</pre>
<pre>
<code>
Story Ref (if any): EOS-18875 UI: Remove last update description field from the UI when it is "unknown_desc" 
</code>
</pre>
<pre>
<code>
No - Unit testing currently done with the Mock data.
</code>
</pre>
<pre>
<code>
- "unknown_desc" is always shown against last update description when we upload or perform software update
</code>
</pre>
<pre>
<code>
- Removed last update description field when 'unknown_desc' is returned in the response.
</code>
</pre>
<pre>
<code>
CSM Login:
- click on maintenance link
- Click on the Software option
- Verify response from 'hotfix/status' API, if description in the response is 'unknown_desc' …
> Eos 19461 remove last update description field from UI if its 'unknown_desc'

- gui/src/components/alerts/alert-large.vue
- gui/src/components/alerts/alert-medium.vue
- gui/src/components/alerts/alert-occurrences.vue
- gui/src/mixins/alerts.ts
<pre>
<code>
Alert severity should be shown same across all pages
</code>
</pre>
<pre>
<code>
Story Ref (if any): EOS-16157: Severity for system full alert is wrong.
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Severity for 90% full alert is shown as red (alert). But alert detail page for that alert shows severity as brown
</code>
</pre>
<pre>
<code>
- Fixed the issue in alert details screen
</code>
</pre>
> [main]EOS-16157: Severity for system full alert is wrong.

- gui/src/components/alerts/alert-medium.vue
- gui/src/components/navigation/nav-bar.vue
- gui/src/router.ts
Disable Health related pages
<pre>
<code>
Disabled health related pages as currently it is unsupported feature
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Helath realted pages show error as it is not supoorted currently
</code>
</pre>
<pre>
<code>
Disabled health related pages
</code>
</pre>
<pre>
<code>
1. Accessed the dashboard. It did not show any error and health summary was not present.
2. Tried accessing health pages. It gave page not found as expected
</code>
</pre>
> Disabled health related pages as currently it is unsupported feature

- gui/src/components/maintenance/auditlog.vue
- gui/src/models/download.ts
- gui/src/store/modules/download.ts
CSM Audit-Log: Audit log should be shown in tabular format
<pre>
<code>
Story Ref (if any): EOS-19474 - CSM Audit-Log: Audit log should be shown in tabular format
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
Current Audit logs are shown in simple text format. This needs to be shown in table.
</code>
</pre>
<pre>
<code>
Added table with pagination and sorting.
</code>
</pre>
<pre>
<code>
</code>
> EOS-19474 - CSM Audit-Log: Audit log should be shown in tabular format

- gui/src/components/maintenance/cortx-about.vue
- gui/src/locales/en.json
GUI: About section shouldbe updated with cluster id and serial number
<pre>
<code>
Story Ref (if any): EOS-19465 UI: Integration Cluster ID field on UI
</code>
</pre>
<pre>
<code>
No - Unit testing is done on Backend developer's machine
</code>
</pre>
<pre>
<code>
- Integration of Cluster ID field on About page.
</code>
</pre>
<pre>
<code>
- Added 'Cluster Id' field to the About page UI.
</code>
</pre>
<pre>
<code>
CSM Login:
- Click on 'Maintenance' link
- Click on 'About' menu
- Verify Cluster Id field on the UI
</code>
> EOS-19465 - Cluster ID integration on About page

- gui/src/components/udx/cortx-iam-user.vue
GUI: After creation of Lyve Pilot I am user, it should show dialog with Access and Secret kay.
<pre>
<code>
Story Ref (if any): EOS-15337 UI: Build: 515 CSM GUI: Lyve Pilot connect registration wizard does not give option for downloading Access key and Secret key while creating new IAM user
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
- Dialog box which contains Access and Secret key for new I am user through Lyve Pilot
</code>
</pre>
<pre>
<code>
- Added dialog box which contains Access and Secret key for new I am user through Lyve Pilot
</code>
</pre>
<pre>
<code>
CSM Login:
- Click on 'Lyve Pilto' link
- Create/select S3 account.
- Create/select bucket.
- Create new I am user by entering user name, password and confirm password fields.
- Verify values …
> EOS-15337 - Added Download and Continue dialog box to show all the details of the newly created I am user account

- gui/src/components/navigation/nav-bar.vue
- gui/src/router.ts
<pre>
<code>
UI: On click of manage link it should not give authorization error
</code>
</pre>
<pre>
<code>
Story Ref (if any): EOS-19095 UI: On click of manage link in S3 account, getting error.
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
- Redirect to correct path on click of manage link in S3 account.
</code>
</pre>
<pre>
<code> 
- Updated logic for manage navigation menu.
- On click of manage link : 
S3 - it should go to '/manage/s3'
CSM - it should go to '/manage'
- It should not give 'Access Denied' error.
</code>
</pre>
<pre>
<code>
CSM Login:
- Click on 'Manage' link
- Click on 'S3 accounts' tab
- Click on 'Manage' link again
- Verify that no access denied error on UI
- Login to S3 UI
- Click on 'I am user' tab
- Click on 'Manage' link again
- …
> EOS-19095 - Updated logic to update manage url path

- gui/src/components/s3/iam-user-management.vue
- gui/src/components/s3/s3.json
S3iamuser deletion Icon is showing tooltip as Delete Account
<pre>
<code>
Story Ref (if any): EOS-20550: UI: S3iamuser deletion Icon is showing as Delete Account.
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
- S3 delete IAM user tooltip on UI is incorrect.
</code>
</pre>
<pre>
<code>
- Added correct tooltip for S3 IAM user delete icon.
</code>
</pre>
<pre>
<code>
CSM Login:
- Login to S3 accounts
- Click on IAM user tab
- Hover on Delete icon in the table
- Verify tooltip
</code>
</pre>
> EOS-20550: Delete IAM user tooltip correction

- gui/src/components/s3/s3.json
S3 account management message text on UI correction
<pre>
<code>
Story Ref (if any): EOS-20547 UI: Stable 175: S3 User Management : Text on UI is incorrect.
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
- S3 User Management text on UI is incorrect.
</code>
</pre>
<pre>
<code>
- Added correct text for S3 user management on S3 accounts tab.
</code>
</pre>
<pre>
<code>
CSM Login:
- Click on Manage link
- Click on S3 account tab
- Verify message under S3 configuration heading
</code>
</pre>
> EOS-20547: S3 account management message text on UI correction

- web/src/config/client_swagger.json
- web/src/config/swagger.json
- web/src/services/api-register.ts
- web/src/services/index.ts
- web/src/services/unsupported_features/routes.ts
- web/src/services/unsupported_features/unsupported-features-controller.ts
<pre>
<code>
Get unsupported features from CSM Agent
</code>
</pre> 
<pre>
<code>
Story Ref (if any): EOS-20700 : unsupported features support on UI
</code>
</pre>
<pre>
<code>
Yes
</code>
</pre>
<pre>
<code>
- API to get the unsupported features from CSM agent.
</code>
</pre>
<pre>
<code>
Added new GET API to get the unsupported features from CSM Agent.
</code>
</pre>
<pre>
<code>
API: /api/v2/unsupported_features
Response: {"unsupported_features":["hctl_node","lyve_pilot","health"]}
</code>
</pre>
Signed-off-by: Soniya Moholkar <soniya.moholkar@seagate.com>
> EOS-20700:NodeJS API to get unsupported features from csm agent

- gui/src/components/widgets/cortx-tabs.vue
<pre>
<code>
EOS-21111:CSM-UI: CSM: Stable#204: Alert tabs must have different IDs
</code>
</pre>
<pre>
<code>
No
</code>
</pre>
<pre>
<code>
'id' attribute for the tabs in alert tabs must have different IDs
</code>
</pre>
Before - 'id' attribute of the tab is not unique
After- 'id' attribute of the tab is unique
<pre>
<code>
Tested whether UI is rendered properly and 'id' attribute is unique for cortx-tab.
</code>
</pre>
> EOS-21111: Unique id for tabs in alert page

- gui/src/common/health-table-headers.ts
- gui/src/common/style.css
> EOS 21407 Adding styles in the table for failed status

- gui/src/components/onboarding/system-config/user-settings/user-setting-local.vue
- _Overview: JIRA number/GitHub Issue added to PR: [Y/N]:_ EOS-22099
- _Describe the problem this patch intends to solve._ Manage user is not able to reset password of users with manage role from csm UI
- _Confirm Testing was performed with installed RPM. Yes/No?_ No
- _Confirm all the ut/regression/smoke test has been …
> EOS-22099 - CSM User reset password issue

- gui/src/components/preboarding/login.vue
- Reset password popup is coming up for s3 account login also. It should only come for csm admin user.
- The API returns reset_password: null for s3account login. Made an explicit check for that.
- _Any northbound interface change and has been notified to other gatekeepers [Y/N]: N
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No? NA
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No? NA
- _Confirm Testing was performed with installed RPM. Yes/No? Yes
- _Confirm all the ut/regression/smoke …
> EOS-23196: Fixed s3account login issue(first time reset password workflow).

- cicd/csm_web.spec
- [EOS-24103](https://jts.seagate.com/browse/EOS-24103)
- Remove SystemD dependency.
- Remove copying of systemd's configuration from the csm_web.spec.
- _Confirm that Test Cases are added (for both the cases, fix and feature). Yes/No?_ Yes
- _Confirm Test Cases cover Happy Path, Non-Happy Path and Scalability. Yes/No?_ Yes
- _Confirm Testing was performed with installed RPM. Yes/No?_ Yes
- _Confirm all the ut/regression/smoke test has been performed [Y/N]_ Y
- _PR is self-reviewed? Yes/No?_ Yes
- _GitHub Issue is updated_ No
- _Jira is updated_ Yes
-  _Check if the description is clear and explained._ Yes
-  _Check Acceptance Criterion is defined._ Yes
-  _All …
> EOS-24103: Remove copying systemd configuration for csm_web.spec

- src/components/shared/LrDataTable/LrDataTable.vue
- data table only had option to show predefined buttons.
-  now we can pass button object and it will show the button on the list.
- making pagination section optional
- option to disable table header button.
- other minor fixes,
> EOS: 29470 - Custom action buttons for data table
